### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by 1e4** [pbbg-io/titan-framework#3]
Permission are not yet seeded. Currently only super admin works, this is simple and just requires a config array then seed it.

Current Permissions:

- crons - To manage the crons
- areas - To manage areas
- menu - To manage the menu
- stats - To manage Stats
- users - To manage users and characters
- groups - To manage groups
- items - To manage items

**Comment by agscs** [comment]
nice built in permision manager in engines is the best, it will be easy to make staff in training ... 
good job.
