### ISSUE TITLE
Ban System

### ISSUE THREAD

**Issue by 1e4** [pbbg-io/titan-framework#5]
Implement both character and user banning.

**Comment by KyleMassacre** [comment]
I am still working on my ban extension. I currently just have a user ban but I can see about character banning

**Comment by KyleMassacre** [comment]
Got all the features working now. I just want to add character banning in the admin area. 
Current Features

- [x] User Ban
- [x] Character Ban
- [x] Redirect Banned Users
- [x] Redirect Banned Characters
- [x] Ban User Via Admin Panel
- [ ] Ban Character Via Admin Panel
- [x] Timed Ban
- [x] Indefinite Ban

**Comment by 1e4** [comment]
Can you make a PR for this when possible?

**Comment by KyleMassacre** [comment]
I could. I was planning on making it an extension but I can add it into the framework

**Comment by 1e4** [comment]
It's something that should be in the core. Banning is pretty normal.

I was also thinking about introducing mute? So communication extentions can
rely on mute to whether the user can communicate

**Comment by KyleMassacre** [comment]
- [x] User Ban
- [x] Character Ban
- [x] Redirect Banned Users
- [x] Redirect Banned Characters
- [x] Ban User Via Admin Panel
- [x] Ban Character Via Admin Panel
- [x] Timed Ban
- [x] Indefinite Ban
